### ISSUE TITLE
32bit compatibility?

### ISSUE THREAD

**Issue by bradkyle** [KxSystems/protobufkdb#25]
Would there be anything impeding the use of protobufkdb with the 32bit version of kdb?

**Comment by nmcdonnell-kx** [comment]
Nothing specifically.  
If there are problems then they're likely to occur with building libprotobuf on 32 bits.  I know Google provide 32 bit versions of protoc on linux, windows and mac.  However, protobufkdb requires the full libprotobuf runtime (with the descriptor and reflection APIs).  Therefore, to avoid C++ ABI incompatibilies we recommend building libprotobuf from source (otherwise you can get strange linking errors).
If you can build libprotobuf and protobufkdb on 32 bit, you're probably okay.

**Comment by bradkyle** [comment]
Thanks
