### ISSUE TITLE
Invalid message field values error on presumably correct values

### ISSUE THREAD

**Issue by bradkyle** [KxSystems/protobufkdb#26]
I'm trying to use protobufkdb to parse the following schema:
```
.protobufkdb.addProtoImportPath["proto/mark/v1"];
.protobufkdb.importProtoFile["mark.proto"];
.protobufkdb.displayMessageSchema[`model.mark.v1.Mark]
message Mark {
  double latpoint = 1;
  double longpoint = 2;
}
.protobufkdb.serializeArrayFromDict[`model.mark.v1.Mark;`latpoint`longpoint!(100f;100f)]
```

> evaluation error:
> 
> Invalid message field values, descriptor: 'model.mark.v1.Mark', expected: 0, received: 9
> 
>   [0] .protobufkdb.serializeArrayFromDict[`model.mark.v1.Mark;`latpoint`longpoint!(100f;100f)]

       ^

Furthermore, I recieve the same result from a list:
`.protobufkdb.serializeArrayFromList[`model.mark.v1.Mark;(100f;100f)]`

> Invalid message field values, descriptor: 'model.mark.v1.Mark', expected: 0, received: 9
> 
>   [0] .protobufkdb.serializeArrayFromDict[`model.mark.v1.Mark;(100f;100f)]

       ^
using:
- ubuntu:18.04
- libprotoc 3.0.0
- built from source with cmake as detailed in docs
- KDB 64bit edition
- protobufkdb version 3014000i

Could someone advise me on how to fix this?
Thanks

**Comment by nmcdonnell-kx** [comment]
The type mapping requires proto messages to be represented as mixed lists.  However, because all your message fields have the same type, q is converting your mixed list to a simple list: (100f;100f) -> (100 100f)
To prevent this conversion you can insert a generic null at the end of the mixed list which protobufkdb will ignore.  

So for lists this should work:
.protobufkdb.serializeArrayFromList[`model.mark.v1.Mark;(100f;100f;::)]
(see the last para in https://code.kx.com/q/interfaces/protobuf/protobuf-types/#protobufq-mapping)

For dictionaries:
.protobufkdb.serializeArrayFromDict[`model.mark.v1.Mark;`latpoint`longpoint`__dummy__!(100f;100f;::)]
(https://code.kx.com/q/interfaces/protobuf/protobuf-types/#representing-messages-as-q-dictionaries , third bullet point)
